//! icons — the Lucide set, ported into typed constants. Reached as `bezel::icons`.
//!
//! ```ignore
//! use ui::icons::{self, navigation};
//!
//! icons::icon(navigation::Compass).size(px(16.0)).text_color(theme.text_muted)
//! ```
//!
//! [`icon`] returns a gpui `Svg`, so it colors with `text_color` and sizes like
//! any element.
//!
//! # The set
//!
//! Modules are Lucide's categories and constants are Lucide's names, both
//! generated by `build.rs` from a pinned release — there is no curated list to
//! drift from upstream. A glyph Lucide files under two categories is one
//! constant re-exported twice, so [`glyph`] holds each exactly once.
//!
//! A constant is the SVG itself rather than a path into an asset source, which
//! is what lets the linker drop an icon the app never names: the set costs a
//! binary only the glyphs it paints. Nothing registers with `with_assets`.
//!
//! # Paying for what you paint
//!
//! One feature per Lucide category, named as Lucide names it, and `full` is all
//! 42. Nothing is on by default. Cargo unions features across a graph, so a
//! category a dependency turns on is the floor for everyone below it — `ui`
//! needs `arrows`, `notifications` and `text`.
//!
//! [`CATEGORIES`] is every enabled category and its icons, for an icon browser.
//! Naming it is what pins the enabled set, so an app that only paints icons
//! never mentions it and keeps the linker's dead-code pass.

mod generated;

pub use generated::*;

use gpui::{Styled as _, Svg, svg};

/// An icon element for a glyph from the set. Size and color are the caller's
/// (`.size(..)`, `.text_color(..)`), matching the `[&_svg]:size-4` idiom.
pub fn icon(glyph: &'static [u8]) -> Svg {
    svg().data(glyph).flex_none()
}

/// The same glyph painted solid. Lucide draws one weight, so this fills the
/// outline rather than reaching for a second drawing: filling *and* stroking
/// keeps the outer edge exactly where [`icon`] puts it, so a control swapping
/// between them — favourited or not — does not jump.
pub fn solid(glyph: &'static [u8]) -> Svg {
    let filled = String::from_utf8_lossy(glyph).replace(r#"fill="none""#, r#"fill="currentColor""#);
    svg().data(filled.as_bytes()).flex_none()
}
