//! Highlights the Syntax page's samples ahead of time.
//!
//! A build script runs on the host whatever the target is, which is the whole
//! trick: `syntax` is tree-sitter, tree-sitter is C, and its C has no libc to
//! compile against for `wasm32-unknown-unknown`. Colouring here and shipping
//! the spans is what lets the web build show the page at all.
//!
//! Native builds read the same table rather than calling the highlighter live,
//! so the two targets cannot disagree about what a sample looks like.

use std::{env, fs, ops::Range, path::Path};

use theme::HighlightKind;

include!("src/patterns/samples.rs");

fn main() {
    println!("cargo:rerun-if-changed=src/patterns/samples.rs");

    let mut out = String::from(
        "// Generated by build.rs from src/patterns/samples.rs — do not edit.\n\
         pub type Span = (std::ops::Range<usize>, theme::HighlightKind);\n\
         pub static HIGHLIGHTS: &[(&str, &str, &[Span])] = &[\n",
    );
    for (tag, _, code) in SAMPLES {
        out.push_str(&format!("    ({tag:?}, {code:?}, &[\n"));
        for (range, kind) in syntax::highlight(code, tag).unwrap_or_default() {
            let Range { start, end } = range;
            out.push_str(&format!(
                "        ({start}..{end}, theme::HighlightKind::{}),\n",
                name(kind)
            ));
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    // The picker's list. Generated for the same reason the spans are: the web
    // build has no `syntax` to enumerate at runtime.
    out.push_str("pub static LANGUAGES: &[&str] = &[\n");
    for lang in syntax::lang::LANGS {
        out.push_str(&format!("    {:?},\n", lang.name));
    }
    out.push_str("];\n");

    let dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&dir).join("highlights.rs"), out).expect("write highlights.rs");
}

/// The variant's own name, since `Debug` is the only thing that knows it and a
/// generated file has to spell it.
fn name(kind: HighlightKind) -> String {
    format!("{kind:?}")
}
